In [1]:
#Numpy Boolean Operations

#Boolean arrays
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [13]:
#tradtional way of selecting array elements-
#Way 1
a[0],a[-1],a[1]

(0, 4, 1)

In [9]:
# multi-index selection of array elements
#Way 2
a[[0, -1 , 1]] # tis returns the 1st, last and second number from the array

array([0, 4, 1])

In [15]:
# boolean array wherein we state true for elements we want to select and false for non-selective elements
#Way 3
a[[True,True,False,False,True]]

array([0, 1, 4])

In [16]:
a >= 2  #the output gives the boolean response whether the elements are satisfying the condition.

array([False, False,  True,  True,  True])

In [17]:
a[a>=2]  # this gives the value of a for the given condition

array([2, 3, 4])

In [18]:
a.mean()

2.0

In [19]:
a[a>a.mean()]

array([3, 4])

In [20]:
a[~(a>a.mean())]  #this gives the element which do no satisfy the condition because of negation sign ~

array([0, 1, 2])

In [21]:
a[(a == 0) | (a ==2)]  # | is used for or condition

array([0, 2])

In [22]:
a[(a%2==0) & (a<=2)]  #& is used for and condition

array([0, 2])

In [38]:
#dynamically creating a matrix

B=np.random.randint(100,size=(2,2))  #100 is the max number until which random integer numbers can be generated
B

array([[76, 25],
       [ 6,  9]])

In [48]:
#Algebra of matrix

C=np.random.randint(10,size=(3,3))
C


array([[5, 9, 1],
       [1, 6, 6],
       [5, 2, 0]])

In [47]:
D=np.random.randint(10,size=(3,3))
D

array([[9, 8, 8],
       [1, 4, 2],
       [6, 4, 2]])

In [51]:
#dot product- scaler product
C.dot(D)

array([[60, 80, 60],
       [51, 56, 32],
       [47, 48, 44]])

In [52]:
#cross product
C @ D

array([[60, 80, 60],
       [51, 56, 32],
       [47, 48, 44]])

In [53]:
#Transpose of matrix C
C.T

array([[5, 1, 5],
       [9, 6, 2],
       [1, 6, 0]])

In [63]:
#useful Numpy functions

#random

np.random.random(size=2)  #this generates 2 random float values

array([0.40757145, 0.18949395])

In [71]:
#normal()- The NumPy random normal function generates a sample of numbers drawn from the normal distribution
#actual syntax- np.random.normal(loc=<mean-value>,scale=<std value>, size=<size of array>)
np.random.normal(size=3)

array([-0.17098369,  0.39815755, -0.72080937])

In [74]:
#rand() in numpy generates random float values for given dimension
np.random.rand(3,4)

array([[0.52016749, 0.89518218, 0.30192646, 0.29963023],
       [0.95089521, 0.12236378, 0.65776679, 0.01461022],
       [0.28120039, 0.41733195, 0.20900565, 0.10050344]])

In [75]:
#arange functions
#this gives the equally spaced numbers upto the param value.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
#this gives a range of values from 5 upto 10 excluding 10
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [77]:
#this lets you specify the interval of which the range of values should be generated as 3rd param
np.arange(0,1,.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [80]:
#here you can have 9 values in the shape of 3*3 matrix
#note- reshape size should fit with the total count of elements
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
#linspace
#this is an alternative to arange()- Return evenly spaced numbers over a specified interval.
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [84]:
np.linspace(0,1,20,False) # If True, return (samples, step), where step is the spacing between samples.

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [85]:
#zeroes, ones, empty
np.zeros(5) #prints those many 0 as the count stated


array([0., 0., 0., 0., 0.])

In [87]:
np.zeros((3,3)) #prints 0 in n dimensional space

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
np.zeros((2,3),dtype= np.int) #this specifies the datatype pf 0 to be int

array([[0, 0, 0],
       [0, 0, 0]])

In [89]:
np.ones(5)  #unit array

array([1., 1., 1., 1., 1.])

In [93]:
np.ones((3,3),dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [94]:
#Return a new array of given shape and type, with random values.
np.empty(3)

array([-0.17098369,  0.39815755, -0.72080937])

In [95]:
#identity and eye
#identitty matrix is built using identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
#eye() is alternative to identity
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.eye(3,3,k=1) #  k>0 means diagonal above main diagonal or vice versa.

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [100]:
"hello world"[6]

'w'