In [16]:
#Operations on Vectors
import numpy as np
a = np.arange(2,10,2)
a
#arange() is an inbuilt numpy function that returns an ndarray object containing evenly spaced values within 
# a defined interval. For instance, you want to create values from 1 to 10; you can use numpy. arange() function.
# Syntax: numpy.arange(start, stop,step)

array([2, 4, 6, 8])

In [7]:
a +10  #note- a array does not update itself. the output shown below is another copy of a until assigned
#also array is an immutable data structure

array([12, 14, 16, 18])

In [8]:
a #as you see, the value of a does not change

array([2, 4, 6, 8])

In [17]:
a +=2  #this is a broadcasting operation where all the elements have been updated and ASSIGNED
a

array([ 4,  6,  8, 10])

In [12]:
l = [1,2,3,4]

[i*10 for i in l]

[10, 20, 30, 40]

In [14]:
b = np.array([1,2,3,4])

In [18]:
a+b

array([ 5,  8, 11, 14])