# Numpy
#refer to https://numpy.org/doc/stable/user/whatisnumpy.html

import sys
import numpy as np

In [ ]:
##working with arrays!

np.array([1,3,5,7])

a = np.array([1,3,5,7])

# if atleast one element is a flot value, the whole datatype of the array becomes float and NOT int
b = np.array([2,4,6,8,1.5])

a[0], a[3]


In [9]:
a[0:]

array([1, 3, 5, 7])

In [10]:
a[:2]

array([1, 3])

In [20]:
b[1:3]

array([4., 6.])

In [21]:
# index -1 is used for getting the last element of the array
b[0],b[2],b[-1]

(2.0, 6.0, 1.5)

In [22]:
#another way of getting the above element is by merging the indexes in [[]]-
b[[0,2,-1]]

array([2. , 6. , 1.5])

In [17]:
# Array Types

a

array([1, 3, 5, 7])

In [23]:
a.dtype

dtype('int32')

In [25]:
b.dtype

dtype('float64')

In [30]:
#typecasting to another datatype
c= np.array([1,2,3,4],dtype = np.float32)
c.dtype

dtype('float32')

In [33]:
#another way of typecasting 
b.dtype = np.int32
b.dtype

dtype('int32')

In [34]:
d = np.array(['a','b','c','d'])
d.dtype

dtype('<U1')

In [37]:
#Dimensions and shapes

#creating a matrix using numpy
A = np.array([
[1,2,3],
[4,5,6],
[7,8,9]])



(3, 3)

In [38]:
#finding the countof rows and columns using shape
A.shape

(3, 3)

In [39]:
#dim gives the dimension of the matrix- in this case it is a 2D matrix
A.ndim

2

In [41]:
#size gives the total number of elements present in the matrix
A.size

9

In [43]:
#Indexing and slicing of matrix

#Square matrix

B = np.array([
    # 0 1 2
     [4,2,9],    #0
     [14,5,6],   #1
     [71,8,9]])  #2

B

array([[ 4,  2,  9],
       [14,  5,  6],
       [71,  8,  9]])

In [44]:
B[1]  # this returns the complete second row of B
#note- the square matrix elements are retrievd with B[row_num][col_num]. If any of the value if absent, it returns the whole row or column accordingly

array([14,  5,  6])

In [57]:
B[0, 1] # this returns the element of 0th row and 1st column

2

In [56]:
B[1:, 1:]

array([[5, 6],
       [8, 9]])

In [60]:
B[1] = np.array([10,10,10]) #changing all 2nd row of Matrix B
B

array([[ 4,  2,  9],
       [10, 10, 10],
       [71,  8,  9]])

In [62]:
B[2]= 99 #this is another way of assigning the whole row
B

array([[ 4,  2,  9],
       [10, 10, 10],
       [99, 99, 99]])

In [63]:
#Summary statistics
a= np.array([1,2,3,4])

a.sum()

10

In [64]:
a.mean()

2.5

In [65]:
a.std()

1.118033988749895

In [66]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])

In [67]:
A.sum()

45

In [68]:
A.mean()

5.0

In [69]:
A.std()

2.581988897471611

In [70]:
A.var()

6.666666666666667

In [72]:
A.sum(axis = 0) # this computes the sum column wise

array([12, 15, 18])

In [ ]:
# A.sum(axis = 1) #this computes the sum row wise